### ISSUE TITLE
Wich version of Java I have to use to execute mail2print?

### ISSUE THREAD

**Issue by gioxx** [t-oster/mail2print#1]
Hello. Java version "1.8.0_221" installed on a Windows 10 machine (in a test environment), when I try to use mail2print I obtain this error:

`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/upstart_it/mail2print/Main has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)`

According to wikipedia (https://en.wikipedia.org/wiki/Java_class_file#General_layout) I should use Java SE 10 to execute your jar file but JRE 10 was deprecated (https://www.oracle.com/technetwork/java/javase/downloads/jre10-downloads-4417026.html) and I can't download it anymore.

Can you tell me how I can use your software?
Thanks in advance.
Giovanni.

**Comment by t-oster** [comment]
Hi, thanks for your interest. Please try the latest Java available (11 or 12?). If it still does not work, here is a version compiled with java 8: https://thomas-oster.de/Mail2Print-1.0-SNAPSHOT-jar-with-dependencies.jar

btw: where did you download the file? I only provided docker-containers as far as I know...

**Comment by gioxx** [comment]
> Hi, thanks for your interest. Please try the latest Java available (11 or 12?). If it still does not work, here is a version compiled with java 8: https://thomas-oster.de/Mail2Print-1.0-SNAPSHOT-jar-with-dependencies.jar

Thanks, I will try on next monday.

> btw: where did you download the file? I only provided docker-containers as far as I know...

From GH! 😄 
https://github.com/t-oster/mail2print/releases

**Comment by gioxx** [comment]
I'm back, sorry for the delay.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
set 04, 2019 12:32:40 PM de.upstart_it.mail2print.Main <init>
INFORMAZIONI: loading Plugins...
set 04, 2019 12:32:41 PM de.upstart_it.mail2print.converter.OfficeConverter <init>
GRAVE: null
java.lang.IllegalStateException: officeHome not set and could not be auto-detected
        at org.jodconverter.office.LocalOfficeUtils.validateOfficeHome(LocalOfficeUtils.java:347)
        at org.jodconverter.office.LocalOfficeManager$Builder.build(LocalOfficeManager.java:137)
        at org.jodconverter.office.LocalOfficeManager.install(LocalOfficeManager.java:71)
        at de.upstart_it.mail2print.converter.OfficeConverter.<init>(OfficeConverter.java:27)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at org.pf4j.DefaultExtensionFactory.create(DefaultExtensionFactory.java:40)
        at org.pf4j.SingletonExtensionFactory.create(SingletonExtensionFactory.java:48)
        at org.pf4j.ExtensionWrapper.getExtension(ExtensionWrapper.java:37)
        at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:575)
        at de.upstart_it.mail2print.Main.getConverter(Main.java:127)
        at de.upstart_it.mail2print.Main.<init>(Main.java:150)
        at de.upstart_it.mail2print.Main.main(Main.java:309)

set 04, 2019 12:32:41 PM de.upstart_it.mail2print.converter.OfficeConverter <init>
INFORMAZIONI: Office Converter disabled.
set 04, 2019 12:32:41 PM de.upstart_it.mail2print.Main lambda$new$0
INFORMAZIONI: Plugin ImageConverter loaded
set 04, 2019 12:32:41 PM de.upstart_it.mail2print.Main lambda$new$0
INFORMAZIONI: Plugin LibreOffice converter loaded
set 04, 2019 12:32:41 PM de.upstart_it.mail2print.Main run
INFORMAZIONI: connecting to mailserver.contoso.com
set 04, 2019 12:32:42 PM de.upstart_it.mail2print.Main main
GRAVE: null
javax.mail.MessagingException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:742)
        at javax.mail.Service.connect(Service.java:366)
        at javax.mail.Service.connect(Service.java:246)
        at de.upstart_it.mail2print.Main.run(Main.java:253)
        at de.upstart_it.mail2print.Main.main(Main.java:310)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
        at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
        at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        at sun.security.ssl.Handshaker.processLoop(Unknown Source)
        at sun.security.ssl.Handshaker.process_record(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:626)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:400)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
        at com.sun.mail.iap.Protocol.<init>(Protocol.java:134)
        at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:131)
        at com.sun.mail.imap.IMAPStore.newIMAPProtocol(IMAPStore.java:763)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:698)
        ... 4 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at sun.security.validator.Validator.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        ... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
        at java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 25 more
```

Obviously mailserver.contoso.com is an example, I obtain the error with a correct IMAP server.
Ciao!
Giovanni.

**Comment by t-oster** [comment]
Can you try imap without SSL? Maybe you have to update Javas certificate store somehow,

**Comment by t-oster** [comment]
https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ
